version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-intl
    versions:
    - 5.10.19
    - 5.11.0
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
    - 5.13.0
    - 5.13.1
    - 5.13.2
    - 5.13.3
    - 5.13.4
    - 5.13.5
    - 5.14.0
    - 5.15.3
    - 5.15.5
    - 5.15.7
    - 5.15.8
    - 5.16.0
    - 5.17.0
    - 5.17.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/codemirror"
    versions:
    - 0.0.107
    - 0.0.108
  - dependency-name: dayjs
    versions:
    - 1.10.4
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
