name: CI Test

on:
  pull_request_target:
    types: [opened, edited, reopened]
  push:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm install
      - run: npm run lint
      - run: npm run cov
        env:
          GITHUB_BRANCH: ${{ github.ref }}
      - uses: codecov/codecov-action@v1
